# Generated by Django 5.1.4 on 2025-01-06 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_user',
            name='address',
            field=models.CharField(default=1, max_length=225),
            preserve_default=False,
        ),
    ]
