# Generated by Django 5.1.4 on 2025-01-06 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realapp', '0002_register_user_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register_user',
            name='address',
        ),
    ]
