# Generated by Django 5.1.4 on 2025-01-06 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realapp', '0003_remove_register_user_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_age', models.IntegerField()),
                ('area', models.CharField(max_length=225)),
                ('balcony', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('hospital_distance', models.FloatField()),
                ('restaurant_distance', models.FloatField()),
                ('amenity', models.CharField(max_length=500)),
                ('school_distance', models.FloatField()),
                ('shopping_distance', models.FloatField()),
            ],
        ),
    ]
