# Generated by Django 5.1.5 on 2025-01-15 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realapp', '0004_house'),
    ]

    operations = [
        migrations.CreateModel(
            name='Construction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=500)),
                ('phone_no', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField(blank=True, null=True)),
                ('established_date', models.DateField()),
                ('license_no', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=10)),
            ],
        ),
    ]
