# Generated by Django 5.1.5 on 2025-01-15 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realapp', '0005_construction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upldprojects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_description', models.CharField(max_length=225)),
                ('project_cost', models.IntegerField()),
                ('project_duration', models.IntegerField()),
                ('project_image', models.ImageField(upload_to='images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realapp.construction')),
            ],
        ),
    ]
