# Generated by Django 5.1.5 on 2025-01-15 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realapp', '0006_upldprojects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upldprojects',
            name='project_cost',
            field=models.CharField(max_length=25),
        ),
    ]
