# Generated by Django 5.1.5 on 2025-01-15 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realapp', '0007_alter_upldprojects_project_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upldprojects',
            name='project_duration',
            field=models.CharField(max_length=25),
        ),
    ]
