# Generated by Django 5.1.6 on 2025-03-04 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realapp', '0008_alter_upldprojects_project_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Designer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('company_address', models.TextField(blank=True, null=True)),
                ('profession', models.CharField(blank=True, choices=[('Interior', 'Interior Design'), ('Exterior', 'Exterior Design')], max_length=100, null=True)),
                ('years_of_experience', models.IntegerField(default=0)),
                ('certifications', models.TextField(blank=True, null=True)),
                ('skills', models.TextField(blank=True, null=True)),
                ('password', models.CharField(max_length=225)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='designer_profile_pics/')),
                ('website', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('design_file', models.FileField(blank=True, null=True, upload_to='designer_designs/')),
                ('image_preview', models.ImageField(blank=True, null=True, upload_to='designer_design_previews/')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('designer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designs', to='realapp.designer')),
            ],
        ),
    ]
